name: Build main & deploy to dev

concurrency: main
on:
  push:
    branches:
      - main
env:
  BASE_IMAGE: ghcr.io/${{ github.repository }}
  DEPLOY_ENABLED: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Run tests & build shadowjar
        run: ./gradlew test shadowjar

  deploy:
    if: DEPLOY_ENABLED == true
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sett tag for docker
        run: |
          echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Bygg & last opp Docker image
        run: |
          docker build --tag ${BASE_IMAGE}:${TAG} --tag ${BASE_IMAGE}:latest .
          docker push ${BASE_IMAGE} --all-tags

      - name: Sett image for nais deploy
        run: echo "IMAGE=${BASE_IMAGE}:${TAG}" >> $GITHUB_ENV

      - name: Deploy til testmiljø
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yaml
